server:
  port: 39146
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${sso.url}/auth/realms/${sso.realm}/protocol/openid-connect/certs
          audiences:
            - ${sso.client}

# Define the local keycloak configuration here
# Deduplication-only property
sso:
  url: http://localhost:8100
  realm: local_realm
  client: local

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  requestLogging: all
  userInfoUri: ${sso.url}/auth/realms/${sso.realm}/protocol/openid-connect/userinfo

captcha:
  hmac-key: secret
  sites:
    test:
      secret: test
