# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: "chill"
  review_status: true
  auto_review:
    enabled: true
    auto_incremental_review: true
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  tools:
    pmd:
      enabled: false
    eslint:
      enabled: false
