name: Require PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  pr-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-checklist@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33