name: Require PR Checklist

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs:
  pr-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-pr-checklist@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
