name: Trivy security scan

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * *" # Daily at 03:00 UTC

jobs:
  scan:
    name: Security check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    if: github.event_name != 'schedule' || github.ref == 'refs/heads/main'
    steps:
      - name: Run Trivy security check on repository
        uses: it-at-m/lhm_actions/action-templates/actions/action-trivy@1f4370c5e243b96e9a90d7569b20b535e24e7c17 # v1.5.1
